title: Blah Blah # your name (or website title) here
logo: "/images/Rick&Morty.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  ... Blah
  <br><br>
  Second description 
  ... Blah Blah
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My Blah Blah Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
